---

- name: install kernell headers
  shell: 'yum install -y "kernel-devel-uname-r == $(uname -r)"'
  register: ps
- debug: var=ps.stdout_lines

- name: install build dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - make
    - wget
    - openssl-devel
    - ncurses-devel
    - newt-devel
    - libxml2-devel
    - gcc
    - gcc-c++
    - sqlite-devel
    - libuuid-devel

- name: remove existing src dir
  file: "path={{ src_dir }} state=absent"

- name: add asterisk user {{ asterisk_user }}
  user:
    name: "{{ asterisk_user }}"

- name: create src directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ asterisk_user }}"
    group: "{{ asterisk_user }}"
    mode: 0775
    recurse: yes
  with_items:
    - "{{ src_dir }}"

- name: download asterisk libpri {{ src.version.libpri }} sources
  unarchive:
    src: "{{ src.url }}/libpri/releases/libpri-{{ src.version.libpri }}.tar.gz"
    dest: "{{ src_dir }}"
    remote_src: yes

- name: download asterisk dahdi {{ src.version.dahdi }} sources
  unarchive:
    src: "{{ src.url }}/dahdi-linux-complete/dahdi-linux-complete-{{ src.version.dahdi }}.tar.gz"
    dest: "{{ src_dir }}"
    remote_src: yes

- name: download asterisk {{ src.version.asterisk }} sources
  unarchive:
    src: "{{ src.url }}/asterisk/releases/asterisk-{{ src.version.asterisk }}.tar.gz"
    dest: "{{ src_dir }}"
    remote_src: yes

# install dahdi
- name: make dahdi {{ src.version.dahdi }}
  command: "make chdir={{ src_dir }}/dahdi-linux-complete-{{ src.version.dahdi }}"
- name: make install dahdi {{ src.version.dahdi }}
  command: make install
  args:
    chdir: "{{ src_dir }}/dahdi-linux-complete-{{ src.version.dahdi }}"
- name: make config dahdi {{ src.version.dahdi }}
  command: make config
  args:
    chdir: "{{ src_dir }}/dahdi-linux-complete-{{ src.version.dahdi }}"

# install pri
- name: make libpri {{ src.version.libpri }}
  command: "make chdir={{ src_dir }}/libpri-{{ src.version.libpri }}"
- name: make install libpri {{ src.version.libpri }}
  command: make install
  args:
    chdir: "{{ src_dir }}/libpri-{{ src.version.libpri }}"

# install asterisk
- name: configure asterisk {{ src.version.asterisk }}
  command: ./configure --libdir=/usr/lib64 CC="gcc -O3" CFLAGS=-O3
  args:
    chdir: "{{ src_dir }}/asterisk-{{ src.version.asterisk }}"

- name: configure asterisk menuselect
  shell: "{{ item }} chdir={{ src_dir }}/asterisk-{{ src.version.asterisk }}"
  with_items:
   - rm menuselect.makeopts || true
   - make menuselect.makeopts
   - sed -ie 's/CORE-SOUNDS-EN-GSM/CORE-SOUNDS-EN-GSM CORE-SOUNDS-RU-GSM/' menuselect.makeopts
   - sed -ie 's/LOADABLE_MODULES/DONT_OPTIMIZE LOADABLE_MODULES/' menuselect.makeopts

- name: building asterisk {{ src.version.asterisk }}
  command: "{{ item }} chdir={{ src_dir }}/asterisk-{{ src.version.asterisk }}"
  with_items:
    - make
    - make install
    - make samples

#- name: Reboot
#    shell: nohup bash -c «sleep 2s && reboot» &
#    when: kernel_update.changed
#    async: 0
#    poll: 0
#    ignore_errors: true
#  register: reboot


